ECDSA Authority
darwinia-network/darwinia-common pull request #1352
Opened 2022-07-26 13:17 UTC by AurevoirXavier

2022-07-27 03:58 UTC, HackFisher commented
Ref: https://eips.ethereum.org/EIPS/eip-712#specification-of-the-eth_signtypeddata-json-rpc

2022-07-27 06:59 UTC, HackFisher commented on frame/bridge/ecdsa-authority/src/lib.rs
> +			network_ids::convert(T::Version::get().spec_name.as_ref())
Sometimes I'm confused with this naming and Ethereum network id.

But this may not be the scope of this PR

2022-07-27 06:59 UTC, HackFisher commented on frame/bridge/ecdsa-authority/src/primitives.rs
> +		// "\x19\x01" + keccak256("EcdsaAuthority()")
Improve domain separator and message part can be simplified

2022-07-28 00:59 UTC, HackFisher approved these changes
cc @furoxr @fewensa We may need companion bridger

2022-07-28 02:03 UTC, hujw77 requested changes

2022-07-28 02:06 UTC, AurevoirXavier commented on frame/bridge/ecdsa-authority/src/lib.rs
> +				*nonce += 1;
Authorities will change immediately.

2022-07-28 02:08 UTC, AurevoirXavier commented on frame/bridge/ecdsa-authority/src/primitives.rs
> +// keccak256("ChangeRelayer(bytes32 network,bytes4 sig,bytes params,uint256 nonce)");
Please update https://github.com/darwinia-network/darwinia-messages-sol/pull/217/files#diff-361b51a9ef5dc5f2704cf644d5a51d09227e70813ff30528100dc83ca80e0d3aR37 first.
This comment comes from there.

2022-07-28 02:09 UTC, AurevoirXavier commented on frame/bridge/ecdsa-authority/src/primitives.rs
> +// keccak256("SignCommitment(bytes32 network,bytes32 commitment,uint256 nonce)");
https://github.com/darwinia-network/darwinia-messages-sol/pull/217/files#diff-1ecbadc6d7b7ea06ff1e541b361c20b60b2ed801bb99400987d53991e7ddfcb6R13-R15

2022-07-28 02:12 UTC, hujw77 commented on frame/bridge/ecdsa-authority/src/primitives.rs
> +// keccak256("ChangeRelayer(bytes32 network,bytes4 sig,bytes params,uint256 nonce)");
OK, I'll update it.

2022-07-28 02:20 UTC, hujw77 commented on frame/bridge/ecdsa-authority/src/lib.rs
> +				*nonce += 1;
Nonce increased should be done after `<AuthoritiesChangeToSign<T>>::put((message, BoundedVec::default()));`
`previous_authority` should sign `nonce`.
If nonce increased immediately, `previous_authority` sign `nonce+1`

2022-07-28 02:30 UTC, AurevoirXavier commented on frame/bridge/ecdsa-authority/src/lib.rs
> +				*nonce += 1;
Fixed

2022-07-28 07:28 UTC, hujw77 requested changes
LGTM, only some types' error.

2022-07-28 07:28 UTC, hujw77 commented on frame/bridge/ecdsa-authority/src/lib.rs
> +						Token::Bytes(RELAY_TYPE_HASH.as_ref().into()),
Bytes --> FixedBytes

2022-07-28 07:28 UTC, hujw77 commented on frame/bridge/ecdsa-authority/src/lib.rs
> +						Token::Bytes(method.id().into()),
Bytes --> FixedBytes

2022-07-28 07:28 UTC, hujw77 commented on frame/bridge/ecdsa-authority/src/lib.rs
> +					Token::Bytes(COMMIT_TYPE_HASH.as_ref().into()),
Bytes --> FixedBytes

2022-07-28 07:28 UTC, hujw77 commented on frame/bridge/ecdsa-authority/src/lib.rs
> +					Token::Bytes(message_root.as_ref().into()),
Bytes --> FixedBytes

2022-07-28 07:28 UTC, hujw77 commented on frame/bridge/ecdsa-authority/src/lib.rs
> +						Token::Uint(require_sign_count),
Swap have no `require_sign_count` changes, so just move it.

2022-07-28 08:26 UTC, merged