Refactor Dust Collector
darwinia-network/darwinia-common pull request #309
Opened 2020-09-24 09:34 UTC by AurevoirXavier

2020-09-24 09:41 UTC, AurevoirXavier commented
Need to check the new account data is compatiable with the old one.

2020-09-24 10:13 UTC, AurevoirXavier commented
The data is ok.

2020-09-24 10:52 UTC, HackFisher requested changes

2020-09-24 10:52 UTC, HackFisher commented on frame/support/src/macros.rs
> +			pub free_ring: Balance,
Prefer to keep as it was.

Old name is ok, there could be migration works and apps compatible issues

2020-09-25 00:51 UTC, AsceticBear approved these changes

2020-09-25 01:55 UTC, HackFisher approved these changes

2020-09-25 01:55 UTC, merged