Added a brief intro to each module
darwinia-network/darwinia-common pull request #790
Opened 2021-08-31 22:35 UTC by robinwei-itering

Check the accuracy the brief description of each module.

2021-09-01 01:36 UTC, AsceticBear requested changes

2021-09-01 01:36 UTC, AsceticBear commented on README.md
> +	- Module of the Ethereum>Darwinia relayer.
Ethereum > Darwinia

2021-09-01 02:12 UTC, AurevoirXavier commented
Recommend to replace *Module* with *Pallet*

2021-09-02 12:54 UTC, AsceticBear approved these changes

2021-09-04 19:51 UTC, merged